[workspace]
authors = ["ilmcconnell <iain.mcconnell@gmail.com>"]
channels = ["conda-forge"]
name = "multi-environment-pixi-workspaces"
platforms = ["osx-64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"

[feature.cpu.dependencies]
pytorch-cpu = "*"

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.target.linux-64.dependencies]
pytorch-gpu = ">=2.7.1,<3"

[feature.gpu.target.win-64.dependencies]
pytorch-gpu = ">=2.7.1,<3"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
